version: "3.7"
services:
        api:
                build: .
                container_name: api
                ports:
                        - "8000:8000"
                depends_on:
                        - mongo

        mongo:
                image: mongo:latest
                container_name: mongo
                volumes:
                        - ~/WP/database:/data/db
                ports:
                        - "27017:27017"
