version: "3"

services:
        api:
                build: .
                container_name: api
                ports:
                        - "8000:8000"
                depends_on:
                        - mongo

        mongo:
                image: mongo:latest
                container_name: mongo
                volumes:
                        - /home/arthur/WP/database:/data/db
                ports:
                        - "27017:27017"
