version: "3"

services:
        api:
                build: .
                container_name: api
                ports:
                        - "8000:8000"
                depends_on:
                        - mongo

        mongo:
                image: mongo:latest
                container_name: mongo
                volumes:
                        - /var/WP/WP-API_DB:/data/db
                        - /var/WP/WP-API_config:/data/configdb
                ports:
                        - "27017:27017"
